postgres:
  host: "localhost"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  db: "ask_app"
  echo: true

auth:
  secret_key: "secret"
  algorithm: "HS256"
  access_token_expire_minutes: 30
